### PR TITLE
Improve code quality by refactoring.

### PR DESCRIPTION
**Pull request by Jainish-123**
### Refactored design smells.

1. **UMLFactory (Your ToDo)** - This is refactored into ClassDiagram and PackageDiagram visitor implementations. For this UMLFactoryUtil, PackageDiagramVisitor, ClassDiagramVisitor class has been created and generateDiagram method is now entry point to create diagram and this method was in UMLDoclet.

2. **Namespace** - To remove cyclic dependency between  Namespace and TypeName, New class NameSpaceService created with contains method and method calling changed from Namespace to NamespaceService in findPackageReferences method of PackageDiagramVisitor class (previously UMLFactory).

3.  **UMLDoclet** - detectPackageDependencyCycles method is moved to DocletConfig class from UMLDoclet class as it is Feature Envy method because it is more intrested  in members of the type: DocletConfig.

### Refactored Implementation smells.

1. **TypeNameWithCardinality** - function method is refactored using extract methods handleArrayType, handleDeclaredType, checkCardinality because it was Complex Method.

2. **JavaBeanProperty** - Constant variables startIndexGetSet and startIndexIs are created in the class to remove Magic numbers from propertyNameOfAccessor method .

3. **TypeName** - Condition decomposed using hasValidLengths, hasValidSeparator variables in getQualified method.

### CODE REVIEW

**Comment by sjoerdtalsma** [comment]
First of all thanks for taking the time to refactor and improve the code.
Unfortunately I cannot accept this pull request for the following reasons:

1. It is too large and contains too many refactorings in a single pull request. This makes reviewing and providing feedback almost impossible.
2. While I agree that the code for `detectPackageDependencyCycles` was a good candidate for refactoring, moving such business method to the `config` package is not where such business logic belongs. Extraction into its own dedicated class would've been better.
3. Too many changes. If you could split up your PR into individual PR's for the refactorings, I would be happy to review them individually, as it is now, it is simply too big a change to oversee from a review perspective.

**Comment by Jainish-123** [comment]
Ok. i will create individual PR. And let me know how it goes.

**Comment by Jainish-123** [comment]
Thanks for your time. I will try to create individual PRs. And let me know
how it goes.
But one request, As i mentioned earlier I have deadline of today so if you
can review you PRs today then It will be really helpful for me.

Thanks.
Jainish Patel

**Comment by Jainish-123** [comment]
Hey I have raised individual PRs(total 4). Let me know how the changes are
If you can review it.

Thanks.
Jainish Patel.

**Comment by sjoerdtalsma** [comment]
Thanks for splitting this up!
I'll close this PR now.

**Pull request closed without merging**
