### PR TITLE
Document the requirement for graphviz

### LINKED ISSUE #112: Please mention the requirement for a local installation of graphviz
The README file currently doesn't state in its `Requirements` that a local installation of graphviz is necessary.

Actually I would very much favor a solution without any dependency on a local installation and therefore see #51 as the actual correct action. But unless this has been done the dependency on graphviz should be  #mentioned.

### PR DESCRIPTION
**Pull request by sjoerdtalsma**
This fixes #112

### CODE REVIEW

**Comment by sjoerdtalsma** [comment]
@hupfdule Could you please take a look if this is what you had in mind?

**Comment by hupfdule** [comment]
Yes, I think this is quite well.

**Comment by hupfdule** [comment]
> @hupfdule Could you please take a look if this is what you had in mind?

Yes, I think this is quite well

**Comment by sjoerdtalsma** [comment]
@hupfdule Thanks for reporting this!

**Pull request merged**
